//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockDownloader.StockDBRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPeak
    {
        public int StockPeakID { get; set; }
        public string Symbol { get; set; }
        public System.DateTime PeakDate { get; set; }
        public int PeakType { get; set; }
        public short TimeFrame { get; set; }
    
        public virtual StockSymbol StockSymbol { get; set; }
    }
}
