//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockDownloader.StockDBRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInformation
    {
        public string Symbol { get; set; }
        public Nullable<decimal> Divident { get; set; }
        public Nullable<decimal> MarKetCap { get; set; }
        public Nullable<decimal> PriceSales { get; set; }
        public Nullable<decimal> PriceBooks { get; set; }
        public Nullable<decimal> PE { get; set; }
        public Nullable<System.DateTime> DivedentPayDay { get; set; }
        public Nullable<decimal> PEG { get; set; }
        public Nullable<decimal> ShortRatio { get; set; }
        public Nullable<decimal> DividentYield { get; set; }
        public Nullable<int> AvgVolume { get; set; }
    
        public virtual StockSymbol StockSymbol { get; set; }
    }
}
