//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockDownloader.StockDBRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockDataEntities : DbContext
    {
        public StockDataEntities()
            : base("name=StockDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<StockInformation> StockInformations { get; set; }
        public DbSet<StockPeak> StockPeaks { get; set; }
        public DbSet<StockPick> StockPicks { get; set; }
        public DbSet<StockPickType> StockPickTypes { get; set; }
        public DbSet<StockQuote> StockQuotes { get; set; }
        public DbSet<StockSymbol> StockSymbols { get; set; }
        public DbSet<StockIndex> StockIndexes { get; set; }
        public DbSet<StockCountry> StockCountries { get; set; }
    }
}
