//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockDownloader.StockDBRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockQuoteExtent
    {
        public string Symbol { get; set; }
        public System.DateTime QuoteDate { get; set; }
        public short Indicator { get; set; }
        public short TimeFrame { get; set; }
        public decimal MA { get; set; }
        public decimal VolumeWeight { get; set; }
        public decimal FromHigh { get; set; }
        public decimal FromLow { get; set; }
        public Nullable<decimal> RSI { get; set; }
        public Nullable<decimal> AvgGain { get; set; }
        public Nullable<decimal> AvgLoss { get; set; }
    }
}
